# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: AuthC Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
#    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS
    runs-on: ubuntu-latest # Service containers only work on ubuntu


    strategy:
      matrix:
        deno: ["v1.x"]
#        os: [macOS-latest, windows-latest, ubuntu-latest]

    services:
      # Label used to access the service container
      AuthC:
        # Docker Hub image
        image: authcompanion/authcompanion:main
        # Env
        env:
          KEY_PATH: ./keyfile
          SECURE: false
          PORT: 3002
        # port
        ports:
          - 3002:3002
        volumes:
          - dbdata:/app/db/

    steps:
      - name: Setup Repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.17.1" 

      - name: Run Integration Tests
        run: deno test -A --unstable
        env:
          KEY_PATH: ./keyfile
          SECURE: false

